name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip==25.0
        pip install -r requirements.txt
    - name: Build torch
      run: |
        python setup.py build
    - name: Install torch
      run: |
        python setup.py install
    - name: Test with pytest
      run: |
        python test/test_torch.py
        python test/test_legacy_nn.py
        python test/test_nn.py
        python test/test_autograd.py
